#' VIPER
#'
#' This function performs Virtual Inference of Protein-activity by Enriched Regulon analysis
#'
#' @param eset ExpressionSet object or Numeric matrix containing the expression data or gene expression signatures, with samples in columns and genes in rows
#' @param regulon Object of class regulon or list of objects of class regulon for metaVIPER analysis
#' @param dnull Numeric matrix for the null model, usually generated by \code{nullTtest}; used by aREA, but not for NaRnEA primary scores
#' @param pleiotropy Logical, whether correction for pleiotropic regulation should be performed
#' @param nes Logical, whether the enrichment score reported should be normalized (NaRnEA returns its proportional enrichment score when FALSE)
#' @param enrichment.method Enrichment algorithm, either aREA (default) or NaRnEA. NaRnEA uses analytic normalization and returns PES when \code{nes=FALSE}; for pleiotropy it applies aREA to shadow regulons.
#' @param method Character string indicating the method for computing the single samples signature, either scale, rank, mad, ttest or none
#' @param bootstraps Integer indicating the number of bootstraps iterations to perform. Only the scale method is implemented with bootstraps.
#' @param minsize Integer indicating the minimum number of targets allowed per regulon
#' @param adaptive.size Logical, whether the weighting scores should be taken into account for computing the regulon size
#' @param eset.filter Logical, whether the dataset should be limited only to the genes represented in the interactome
#' #' @param mvws Number or vector indicating either the exponent score for the metaViper weights, or the inflection point and trend for the sigmoid function describing the weights in metaViper
#' @param pleiotropyArgs list of 5 numbers for the pleotropy correction indicating: regulators p-value threshold, pleiotropic interaction p-value threshold, minimum number of targets in the overlap between pleiotropic regulators, penalty for the pleiotropic interactions and the method for computing the pleiotropy, either absolute or adaptive
#' @param cores Integer number of worker processes. Values above 1 use PSOCK on Windows and fork workers on Unix. Nested VIPER calls share one worker layer.
#' @param verbose Logical, whether progression messages should be printed in the terminal
#' @return A matrix of inferred activity for each regulator gene in the network across all samples
#' @details Set \code{cores > 1} to enable multicore execution. Windows uses PSOCK workers; Unix-like systems use fork workers. Nested calls reuse the active worker layer. Windows worker copies are limited by \code{getOption("viper.max.parallel.memory", 64 * 1024^3)}; set this option to adjust the aggregate input-copy budget.
#' @seealso \code{\link{msviper}}
#' @examples
#' data(bcellViper, package="bcellViper")
#' d1 <- exprs(dset)
#' res <- viper(d1, regulon)
#' dim(d1)
#' d1[1:5, 1:5]
#' regulon
#' dim(res)
#' res[1:5, 1:5]
#' @export

viper <- function(eset, regulon, dnull=NULL, pleiotropy=FALSE, nes=TRUE, method=c("none", "scale", "rank", "mad", "ttest"), bootstraps=0, minsize=25, adaptive.size=FALSE, eset.filter=TRUE, mvws=1, pleiotropyArgs=list(regulators=.05, shadow=.05, targets=10, penalty=20, method="adaptive"), cores=1, verbose=TRUE, enrichment.method=c("aREA", "NaRnEA")) {
    method <- match.arg(method)
    enrichment.method <- match.arg(enrichment.method)
    pdata <- NULL
    if (is(eset, "viperSignature")) {
        dnull <- eset$nullmodel
        eset <- eset$signature
        method="none"
        if (bootstraps>0) {
            bootstraps <- 0
            warning("Using a null model, bootstraps iterations are ignored.", call.=FALSE)
        }
    }
    if (pleiotropy & bootstraps>0) {
        bootstraps <- 0
        warning("Using pleiotropic correction, bootstraps iterations are ignored.", call.=FALSE)
    }
    if (is(eset, "ExpressionSet")) {
        pdata <- phenoData(eset)
        eset <- exprs(eset)
    } else if (is.data.frame(eset)) {
        eset <- as.matrix(eset)
    }
    if (is.null(nrow(eset))) eset <- matrix(eset, length(eset), 1, dimnames=list(names(eset), NULL))
    if (verbose) message("\nComputing the association scores")
    if (names(regulon[[1]])[1]=="tfmode") regulon <- list(regulon=regulon)
    if (bootstraps>0) {
        return(bootstrapViper(eset=eset, regulon=regulon, nes=nes, bootstraps=bootstraps, eset.filter=eset.filter, adaptive.size=adaptive.size, minsize=minsize, cores=cores, verbose=verbose))
    }
    cores1 <- 1
    if (length(regulon)>1) {
        cores1 <- min(cores, length(regulon))
        nes <- TRUE # Only NES can be returned in metaViper
    }
    if (cores>1 | cores1>1) verbose <- FALSE # Set verbose to FALSE if running in multiple cores
    switch(method,
           scale={tt <- t(scale(t(eset)))},
           rank={tt <- fastRowRanks(eset)*punif(length(eset), -.1, .1)},
           mad={tt <- t(apply(eset, 1, function(x) (x-median(x))/mad(x)))},
           ttest={
               tt <- sapply(1:ncol(eset), function(i, eset) rowTtest(eset[, i]-eset[, -i])$statistic, eset=eset)
               colnames(tt) <- colnames(eset)
               rownames(tt) <- rownames(eset)
           },
           none={tt <- eset}
    )
    if (verbose) message("Computing regulons enrichment with ", enrichment.method)
    if (enrichment.method == "NaRnEA" && !is.null(dnull)) {
        if (pleiotropy) warning("NaRnEA uses analytic normalization for primary scores; dnull is used only to calibrate aREA shadow scores.", call.=FALSE)
        else warning("NaRnEA uses analytic normalization; dnull is ignored for this enrichment method.", call.=FALSE)
    }
    res <- .viperParallelApply(regulon, function(regulon, dnull, pleiotropy, nes, tt, eset.filter, adaptive.size, cores, pleiotropyArgs, verbose, enrichment.method, sample.names) {
                                    
        if (eset.filter) {
            tmp <- c(names(regulon), unlist(lapply(regulon, function(x) names(x$tfmode)), use.names=FALSE))
            tt <- tt[rownames(tt) %in% unique(tmp), ]
        }
        regulon <- lapply(regulon, function(x, genes) {
            filtro <- names(x$tfmode) %in% genes
            x$tfmode <- x$tfmode[filtro]
            if (length(x$likelihood)==length(filtro)) x$likelihood <- x$likelihood[filtro]
            return(x)
        }, genes=rownames(tt))
        if (adaptive.size) regulon <- regulon[sapply(regulon, function(x) {
            sum((x$likelihood/max(x$likelihood))^2)
        })>=minsize]
        else regulon <- regulon[sapply(regulon, function(x) length(x$tfmode))>=minsize]
        if (enrichment.method == "NaRnEA") es <- matrixNaRnEA.viper(tt, regulon, minsize=0, cores=cores)
        else es <- aREA(tt, regulon, cores=cores, minsize=0, verbose=verbose)
        if (!nes) {
            if (pleiotropy) warning("No pleiotropy correction implemented when raw es is returned.", call.=FALSE)
            if (pleiotropy) return(es$es)
            if (enrichment.method == "NaRnEA") return(es$pes)
            return(es$es)
        }
        if (enrichment.method == "NaRnEA") {
            nes <- es$nes
            if (pleiotropy) warning("Pleiotropy correction uses aREA on shadow regulons when enrichment.method='NaRnEA'.", call.=FALSE)
        }
        else if (is.null(dnull)) nes <- es$nes
        else {
            if (verbose) message("\nEstimating NES with null model")
            tmp <- aREA(dnull, regulon, cores=cores, minsize=0, verbose=verbose)$es
            if (ncol(tmp)>499) {
                nes <- t(sapply(1:nrow(tmp), function(i, tmp, es) {
                    #aecdf1(tmp[i, ], symmetric=TRUE, es[i, ])$nes
                    aecdf(tmp[i, ], symmetric=TRUE)(es[i, ])$nes
                }, tmp=tmp, es=es$es))
                rownames(nes) <- rownames(es$nes)
            }
            else {
                nes <- es$es/sqrt(frvarna(tmp)[, 1])
            }
        }
        if (pleiotropy) {
            pb <- NULL
            if (verbose) {
                message("\nComputing pleiotropy for ", ncol(nes), " samples.")
                message("\nProcess started at ", date())
            }
            if (cores>1) {
                nes <- .viperParallelApply(1:ncol(nes), function(i, ss, nes, regulon, args, dnull) {
                    nes <- nes[, i]
                    sreg <- shadowRegulon(ss[, i], nes, regulon, regulators=args[[1]], shadow=args[[2]], targets=args[[3]], penalty=args[[4]], method=args[[5]])
                    if (!is.null(sreg)) {
                        if (is.null(dnull)) tmp <-aREA(ss[, i], sreg, minsize=5, cores=1)$nes[, 1]
                        else {
                            tmp <- aREA(cbind(ss[, i], dnull), sreg, minsize=5, cores=1)$es
                            #tmp <- apply(tmp, 1, function(x) aecdf1(x[-1], symmetric=TRUE, x[1])$nes)
                            tmp <- apply(tmp, 1, function(x) aecdf(x[-1], symmetric=TRUE)(x[1])$nes)
                        }
                        nes[match(names(tmp), names(nes))] <- tmp
                    }
                    return(nes)
                }, ss=tt, nes=nes, regulon=regulon, args=pleiotropyArgs, dnull=dnull, mc.cores=cores)
                nes <- sapply(nes, function(x) x)    
            }
            else {
                if (verbose) pb <- txtProgressBar(max=ncol(nes), style=3)
                nes <- sapply(1:ncol(nes), function(i, ss, nes, regulon, args, dnull, pb) {
                    nes <- nes[, i]
                    sreg <- shadowRegulon(ss[, i], nes, regulon, regulators=args[[1]], shadow=args[[2]], targets=args[[3]], penalty=args[[4]], method=args[[5]])
                    if (!is.null(sreg)) {
                        if (is.null(dnull)) tmp <-aREA(ss[, i], sreg, minsize=5)$nes[, 1]
                        else {
                            tmp <- aREA(cbind(ss[, i], dnull), sreg, minsize=5)$es
                            #tmp <- apply(tmp, 1, function(x) aecdf1(x[-1], symmetric=TRUE, x[1])$nes)
                            tmp <- apply(tmp, 1, function(x) aecdf(x[-1], symmetric=TRUE)(x[1])$nes)
                        }
                        nes[match(names(tmp), names(nes))] <- tmp
                    }
                    if (is(pb, "txtProgressBar")) setTxtProgressBar(pb, i)    
                    return(nes)
                }, ss=tt, nes=nes, regulon=regulon, args=pleiotropyArgs, dnull=dnull, pb=pb)
            }
            if (verbose) message("\nProcess ended at ", date(), "\n")
            if (is.null(nrow(nes))) nes <- matrix(nes, length(nes), 1, dimnames=list(names(nes), NULL))
            colnames(nes) <- sample.names
            return(nes)
        }
        return(nes)
    }, dnull=dnull, pleiotropy=pleiotropy, nes=nes, tt=tt, eset.filter=eset.filter, adaptive.size=adaptive.size, cores=cores, pleiotropyArgs=pleiotropyArgs, verbose=verbose, enrichment.method=enrichment.method, sample.names=colnames(eset), mc.cores=cores1)
    if (length(res)==1) nes <- res[[1]]
    else {
        genes <- unique(unlist(lapply(res, rownames), use.names=FALSE))
        nes <- sapply(res, function(x, genes) as.vector(x[match(genes, rownames(x)), ]), genes=genes)
        nes[is.na(nes)] <- 0
        if (length(mvws)==1) {
            ws <- abs(nes)^mvws
        }
        else {
            ws <- sigT(abs(nes), mvws[2], mvws[1])
        }
        nes <- matrix(rowSums(nes*ws)/rowSums(ws), length(genes), ncol(res[[1]]), dimnames=list(genes, colnames(res[[1]])))
    }
    if (is.null(pdata)) return(nes)
    return(ExpressionSet(assayData=nes, phenoData=pdata))
}

##########
#' Generic S4 method for signature and sample-permutation null model for VIPER
#' 
#' This function generates a viperSignature object from a test dataset based on a set of samples to use as reference
#' 
#' @param eset ExpressionSet object or numeric matrix containing the test dataset, with genes in rows and samples in columns
#' @param ... Additional parameters added to keep compatibility
#' @return viperSignature S3 object containing the signature and null model
#' @export
#' @docType methods
#' @rdname viperSignature-methods
setGeneric("viperSignature", function(eset, ...) standardGeneric("viperSignature"))

#' @param pheno Character string indicating the phenotype data to use
#' @param refgroup Vector of character string indicatig the category of \code{pheno} to use as reference group
#' @param method Character string indicating how to compute the signature and null model, either ttest, zscore or mean
#' @param per Integer indicating the number of sample permutations
#' @param bootstrap Logical, whether null model should be estimated with bootstrap. In this case, only reference samples are used.
#' @param seed Integer indicating the seed for the random sample generation. The system default is used when set to zero
#' @param cores Integer number of worker processes. Values above 1 use PSOCK on Windows and fork workers on Unix.
#' @param verbose Logical, whether progression messages should be printed in the terminal
#' @examples
#' data(bcellViper, package="bcellViper")
#' ss <- viperSignature(dset, "description", c("N", "CB", "CC"), per=100) # Only 100 permutations to reduce computation time, but it is recommended to perform at least 1000 permutations
#' res <- viper(ss, regulon)
#' dim(exprs(dset))
#' exprs(dset)[1:5, 1:5]
#' regulon
#' dim(res)
#' exprs(res)[1:5, 1:5]
#' @rdname viperSignature-methods
#' @aliases viperSignature,ExpressionSet-method
setMethod("viperSignature", "ExpressionSet", function(eset, pheno, refgroup, method=c("zscore", "ttest", "mean"), per=100, bootstrap=TRUE, seed=1, cores=1, verbose=TRUE) {
    method <- match.arg(method)
    pos <- pData(eset)[[pheno]] %in% refgroup
    tmp <- viperSignature(exprs(eset)[, !pos], exprs(eset)[, pos], method=method, bootstrap=bootstrap, per=per, seed=seed, cores=cores, verbose=verbose)
    pdata <- phenoData(eset)
    pData(pdata) <- pData(pdata)[match(colnames(tmp$signature), rownames(pData(pdata))), ]
    tmp$signature <- ExpressionSet(assayData=tmp$signature, phenoData=pdata)
    return(tmp)
})

#' @param ref Numeric matrix containing the reference samples (columns) and genes in rows
#' @examples
#' data(bcellViper, package="bcellViper")
#' d1 <- exprs(dset)
#' pos <- pData(dset)[["description"]] %in% c("N", "CB", "CC")
#' ss <- viperSignature(d1[, !pos], d1[, pos], per=100) # Only 100 permutations to reduce computation time, but it is recommended to perform at least 1000 permutations
#' res <- viper(ss, regulon)
#' dim(d1)
#' d1[1:5, 1:5]
#' regulon
#' dim(res)
#' res[1:5, 1:5]
#' @rdname viperSignature-methods
#' @aliases viperSignature,matrix-method
setMethod("viperSignature", "matrix", function(eset, ref, method=c("zscore", "ttest", "mean"), per=100, bootstrap=TRUE, seed=1, cores=1, verbose=TRUE) {
    method <- match.arg(method)
    if (cores > 1) verbose <- FALSE
    if (seed>0) set.seed(ceiling(seed))
    switch(method,
    ttest={
        vpsig <- .viperParallelApply(seq_len(ncol(eset)), function(i, eset, ref) {
            tmp <- rowTtest(eset[, i]-ref)
            (qnorm(tmp$p.value/2, lower.tail=FALSE)*sign(tmp$statistic))[, 1]
        }, eset=eset, ref=ref, mc.cores=cores)
        vpsig <- do.call(cbind, vpsig)
        rownames(vpsig) <- rownames(eset)
        colnames(vpsig) <- colnames(eset)
    },
    zscore={
        vpsig <- (eset-rowMeans(ref))/sqrt(frvarna(ref)[, 1])
    },
    mean={
        vpsig <- eset-rowMeans(ref)
    })
    if (bootstrap) {
        if (ncol(ref)<6) {
            vpnull <- NULL
            warning("Not enough samples to compute null model by sample permutation, gene permutation will be used instead", call.=FALSE)
        }
        else {
            per <- ceiling(per/ncol(ref)) # Number of bootstraps
            pb <- NULL
            if (verbose && cores <= 1) pb <- txtProgressBar(max=ncol(ref), style=3)
            tmp <- .viperParallelApply(1:ncol(ref), function(i, d22, per, method, pb) { # Leave one out vs. bootstrap set
                tmp <- sapply(1:per, function(i, x, y, method) {
                    pos <- sample(ncol(y), replace=TRUE)
                    y <- y[, pos]
                    switch(method,
                    ttest={
                        dnull <- rowTtest(x-y)
                        dnull <- qnorm(dnull$p.value[, 1]/2, lower.tail=FALSE)*sign(dnull$statistic[, 1])
                    },
                    zscore={
                        dnull <- (x-rowMeans(y))/sqrt(frvarna(y)[, 1])
                    },
                    mean={
                        dnull <- x-rowMeans(y)
                    })
                }, x=d22[, i], y=d22[, -i], method=method)
                if (!is.null(pb)) setTxtProgressBar(pb, i)
                return(tmp)
            }, d22=ref, per=per, method=method, pb=pb, mc.cores=cores)
            vpnull <- do.call(cbind, tmp)
        }
    }
    else {
        if ((ncol(eset)+ncol(ref))<12) {
            vpnull <- NULL
            warning("Not enough samples to compute null model by sample permutation, gene permutation will be used instead", call.=FALSE)
        }
        else {
            if (ncol(ref)<12) {
                warning("Not enough reference samples to compute null model, all samples will be used", call.=FALSE)
                ref <- cbind(ref, eset)
            }
            nco <- choose(ncol(ref), round(ncol(ref)/2))
            if (nco<(50*per)) {
                per1 <- combn(sample(ncol(ref)), round(ncol(ref)/2))[, 1:min(per, nco)]
            }
            else {
                per1 <- sapply(1:(min(per, nco)), function(i, n1, n2) sample(n1, n2), n1=ncol(ref), n2=round(ncol(ref)/2))
            }
            pb <- NULL
            if (cores>1) {
                vpnull <- .viperParallelApply(1:ncol(per1), function(i, eset, ref, size, method, per1) {
                    switch(method,
                           ttest={
                               tmp <- NA
                               while(any(is.na(tmp))) {
                                   pos <- sample(ncol(eset)+ncol(ref), size)
                                   x <- if (pos[1] <= ncol(eset)) eset[, pos[1]] else ref[, pos[1]-ncol(eset)]
                                   ypos <- pos[-1]
                                   y <- do.call(cbind, lapply(ypos, function(j) {
                                       if (j <= ncol(eset)) eset[, j] else ref[, j-ncol(eset)]
                                   }))
                                   tmp <- rowTtest(x-y)
                                   tmp <- (qnorm(tmp$p.value/2, lower.tail=FALSE)*sign(tmp$statistic))[, 1]
                               }
                           },
                           zscore={
                               pos <- per1[, i]
                               tmp <- (rowMeans(ref[, pos])-rowMeans(ref[, -pos]))/(sqrt(frvarna(ref[, pos])[, 1])+sqrt(frvarna(ref[, -pos])[, 1]))
                           },
                           mean={
                               pos <- per1[, i]
                               tmp <- rowMeans(ref[, pos])-rowMeans(ref[, -pos])
                           })
                    return(tmp)
                }, eset=if (method == "ttest") eset else NULL, ref=ref, size=ncol(ref)+1, method=method, per1=per1, mc.cores=cores)
                vpnull <- sapply(vpnull, function(x) x)    
            }
            else {
                if (verbose) pb <- txtProgressBar(max=ncol(per1), style=3)
                vpnull <- sapply(1:ncol(per1), function(i, dset, ref, pb, size, verbose, method, per1) {
                    if (verbose) setTxtProgressBar(pb, i)
                    switch(method,
                    ttest={
                        tmp <- NA
                        while(any(is.na(tmp))) {
                            pos <- sample(ncol(dset), size)
                            tmp <- rowTtest(dset[, pos[1]]-dset[, pos[-1]])
                            tmp <- (qnorm(tmp$p.value/2, lower.tail=FALSE)*sign(tmp$statistic))[, 1]
                        }
                    },
                    zscore={
                        pos <- per1[, i]
                        tmp <- (rowMeans(ref[, pos])-rowMeans(ref[, -pos]))/(sqrt(frvarna(ref[, pos])[, 1])+sqrt(frvarna(ref[, -pos])[, 1]))
                    },
                    mean={
                        pos <- per1[, i]
                        tmp <- rowMeans(ref[, pos])-rowMeans(ref[, -pos])
                    })
                    return(tmp)
                }, dset=cbind(eset, ref), ref=ref, size=ncol(ref)+1, pb=pb, verbose=verbose, method=method, per1=per1)
            }
            rownames(vpnull) <- rownames(eset)
        }
    }
    tmp <- list(signature=vpsig, nullmodel=vpnull)
    class(tmp) <- "viperSignature"
    return(tmp)
})

#' bootstrapsViper
#' 
#' This function performs a viper analysis with bootstraps
#' 
#' @param eset ExpressionSet object or Numeric matrix containing the expression data, with samples in columns and genes in rows
#' @param regulon Object of class regulon
#' @param nes Logical, whether the enrichment score reported should be normalized
#' @param bootstraps Integer indicating the number of bootstraps iterations to perform. Only the scale method is implemented with bootstraps.
#' @param eset.filter Logical, whether the dataset should be limited only to the genes represented in the interactome
#' @param adaptive.size Logical, whether the weighting scores should be taken into account for computing the regulon size
#' @param minsize Integer indicating the minimum number of targets allowed per regulon
#' @param mvws Number or vector indicating either the exponent score for the metaViper weights, or the inflection point and trend for the sigmoid function describing the weights in metaViper
#' @param cores Integer number of worker processes. Values above 1 use PSOCK on Windows and fork workers on Unix.
#' @param verbose Logical, whether progression messages should be printed in the terminal
#' @return A list containing a matrix of inferred activity for each regulator gene in the network across all samples and the corresponding standard deviation computed from the bootstrap iterations.
#' @seealso \code{\link{viper}}
#' @examples
#' data(bcellViper, package="bcellViper")
#' d1 <- exprs(dset)
#' res <- viper(d1[, 1:50], regulon, bootstraps=10) # Run only on 50 samples to reduce computation time
#' dim(d1)
#' d1[1:5, 1:5]
#' regulon
#' dim(res$nes)
#' res$nes[1:5, 1:5]
#' res$sd[1:5, 1:5]
bootstrapViper <- function(eset, regulon, nes=TRUE, bootstraps=10, eset.filter=FALSE, adaptive.size=TRUE, minsize=20, mvws=1, cores=1, verbose=TRUE) {
    cores1 <- 1
    if (length(regulon)>1) {
        cores1 <- min(cores, length(regulon))
        nes <- TRUE # Only NES can be returned in metaViper
    }
    if (cores>1 | cores1>1) verbose <- FALSE # Set verbose to FALSE if running in multiple cores
    if (verbose) {
        message("\nComputing the parameters for ", bootstraps, " bootstraps.")
        message("Process started at ", date())
    }
    tmp <- lapply(1:bootstraps, function(i, eset) {
        tmp <- eset[, sample(ncol(eset), replace=TRUE)]
        return(list(mean=rowMeans(tmp), sd=sqrt(frvarna(tmp)[, 1])))
    }, eset=eset)
    btmean <- sapply(tmp, function(x) x$mean)
    btsd <- sapply(tmp, function(x) x$sd)
    res <- .viperParallelApply(regulon, function(regulon, eset, btmean, btsd, cores, verbose, eset.filter, adaptive.size, minsize) {
        if (eset.filter) {
            tmp <- c(names(regulon), unlist(lapply(regulon, function(x) names(x$tfmode)), use.names=FALSE))
            eset <- eset[rownames(eset) %in% unique(tmp), ]
        }
        regulon <- lapply(regulon, function(x, genes) {
            filtro <- names(x$tfmode) %in% genes
            x$tfmode <- x$tfmode[filtro]
            if (length(x$likelihood)==length(filtro)) x$likelihood <- x$likelihood[filtro]
            return(x)
        }, genes=rownames(eset))
        if (adaptive.size) regulon <- regulon[sapply(regulon, function(x) {
            sum((x$likelihood/max(x$likelihood))^2)
        })>=minsize]
        else regulon <- regulon[sapply(regulon, function(x) length(x$tfmode))>=minsize]
        targets <- unique(unlist(lapply(regulon, function(x) names(x$tfmode)), use.names=FALSE))
        mor <- sapply(regulon, function(x, genes) {
            return(x$tfmode[match(genes, names(x$tfmode))])
        }, genes=targets)
        wts <- sapply(regulon, function(x, genes) {
            tmp <- x$likelihood[match(genes, names(x$tfmode))]
            tmp[is.na(match(genes, names(x$tfmode)))] <- NA
            return(tmp/max(tmp, na.rm=T))
        }, genes=targets)
        mor[is.na(mor)] <- 0
        wts[is.na(wts)] <- 0
        rownames(wts) <- targets
        nes <- sqrt(colSums(wts^2))
        wts <- scale(wts, center=FALSE, scale=colSums(wts))
        postemp <- match(rownames(wts), rownames(btmean))
        btmean <- btmean[postemp, ]
        btsd <- btsd[postemp, ]
        pb <- NULL
        if (cores>1) {
            res <- .viperParallelApply(1:ncol(eset), function(i, eset, btmean, btsd, mor, wts) {
                tt <- (eset[, i]-btmean)/btsd
                tt <- apply(tt, 2, function(x) rank(x))/(nrow(tt)+1)
                t1 <- abs(tt-.5)*2
                t1 <- t1+(1-max(t1))/2
                t1 <- qnorm(t1)
                t2 <- qnorm(tt)
                sum1 <- t(mor * wts) %*% t2
                sum2 <- t((1-abs(mor)) * wts) %*% t1
                ss <- sign(sum1)
                ss[ss==0] <- 1
                tmp <- (abs(sum1) + sum2*(sum2>0))*ss
                return(list(mean=rowMeans(tmp), sd=sqrt(frvarna(tmp)[, 1])))
            }, eset=eset, btmean=btmean, btsd=btsd, mor=mor, wts=wts, mc.cores=cores)
        }
        else {
            if (verbose) pb <- txtProgressBar(max=ncol(eset), style=3)
            res <- lapply(1:ncol(eset), function(i, eset, btmean, btsd, mor, wts, pb) {
                tt <- (eset[, i]-btmean)/btsd
                tt <- apply(tt, 2, function(x) rank(x))/(nrow(tt)+1)
                t1 <- abs(tt-.5)*2
                t1 <- t1+(1-max(t1))/2
                t1 <- qnorm(t1)
                t2 <- qnorm(tt)
                sum1 <- t(mor * wts) %*% t2
                sum2 <- t((1-abs(mor)) * wts) %*% t1
                ss <- sign(sum1)
                ss[ss==0] <- 1
                tmp <- (abs(sum1) + sum2*(sum2>0))*ss
                if (is(pb, "txtProgressBar")) setTxtProgressBar(pb, i)    
                return(list(mean=rowMeans(tmp), sd=sqrt(frvarna(tmp)[, 1])))
            }, eset=eset, btmean=btmean, btsd=btsd, mor=mor, wts=wts, pb=pb)
        }
        names(res) <- colnames(eset)
        if (verbose) message("\nProcess ended at ", date())
        return(list(nes=sapply(res, function(x) x$mean)*nes, sd=sapply(res, function(x) x$sd)*nes))
    }, btmean=btmean, eset=eset, btsd=btsd, cores=cores, verbose=verbose, eset.filter=eset.filter, adaptive.size=adaptive.size, minsize=minsize, mc.cores=cores1)    
    if (length(res)==1) return(res[[1]])
    genes <- unique(unlist(lapply(res, function(x) rownames(x$nes)), use.names=FALSE))
    nes <- sapply(res, function(x, genes) as.vector(x$nes[match(genes, rownames(x$nes)), ]), genes=genes)
    nessd <- sapply(res, function(x, genes) as.vector(x$sd[match(genes, rownames(x$sd)), ]), genes=genes)
    nes[is.na(nes)] <- 0
    nessd[is.na(nessd)] <- 0
    if (length(mvws)==1) {
        ws <- abs(nes)^mvws
    }
    else {
        ws <- sigT(abs(nes), mvws[2], mvws[1])
    }
    nes <- matrix(rowSums(nes*ws)/rowSums(ws), length(genes), ncol(res[[1]]$nes), dimnames=list(genes, colnames(res[[1]]$nes)))
    nessd <- matrix(rowSums(nessd*ws)/rowSums(ws), length(genes), ncol(res[[1]]$sd), dimnames=list(genes, colnames(res[[1]]$sd)))
    return(list(nes=nes, sd=nessd))
}

# Internal vectorized NaRnEA kernel. Regulon matrices are sparse; only rank/sign
# matrices scale with the full gene-by-sample input.
.viperNaRnEAChunk <- function(task) {
    X <- task$X; U <- task$U; R <- task$R; S <- task$S
    max.du <- task$max.du; g <- task$g
    n <- ncol(R); r <- ncol(X)
    Er <- (g + 1) / 2; Er2 <- (2 * g^2 + 3 * g + 1) / 6
    Ers <- colSums(R * S) / g; Er2s <- colSums(R * R * S) / g
    D <- as.matrix(Matrix::crossprod(X, R * S))
    De <- outer(as.numeric(Matrix::colSums(X)), Ers)
    Dv <- outer(as.numeric(Matrix::colSums(X * X)), Er2 - Ers^2)
    V <- as.matrix(Matrix::crossprod(U, R))
    Ve <- matrix(as.numeric(Matrix::colSums(U)) * Er, nrow=r, ncol=n)
    Vv <- outer(as.numeric(Matrix::colSums(U * U)), rep(Er2 - Er^2, n))
    cv0 <- as.numeric(Matrix::colSums(X * U))
    covariance <- outer(cv0, Er2s - Ers * Er) / sqrt(Dv * Vv)
    Dnes <- (D - De) / sqrt(Dv); Vnes <- (V - Ve) / sqrt(Vv)
    nesp <- (Dnes + Vnes) / sqrt(2 + 2 * covariance)
    nesm <- (Dnes - Vnes) / sqrt(2 - 2 * covariance)
    pp <- pnorm(nesp, lower.tail=FALSE, log.p=TRUE); pm <- pnorm(nesm, lower.tail=TRUE, log.p=TRUE)
    positive <- pp < pm; lp <- ifelse(positive, pp, pm)
    finalp <- lp + log(2) + log1p(exp(lp) / -2)
    nes <- ifelse(positive, qnorm(finalp - log(2), lower.tail=FALSE, log.p=TRUE),
                  qnorm(finalp - log(2), lower.tail=TRUE, log.p=TRUE))
    pd <- (matrix(max.du[, 1], r, n) - De) / sqrt(Dv)
    pu <- (matrix(max.du[, 2], r, n) - Ve) / sqrt(Vv)
    plus <- (pd + pu) / sqrt(2 + 2 * covariance)
    pplus <- pnorm(plus, lower.tail=FALSE, log.p=TRUE)
    pplus <- pplus + log(2) + log1p(exp(pplus) / -2)
    maxpos <- qnorm(pplus - log(2), lower.tail=FALSE, log.p=TRUE)
    pnd <- (-matrix(max.du[, 1], r, n) - De) / sqrt(Dv)
    minus <- (pnd - pu) / sqrt(2 - 2 * covariance)
    pminus <- pnorm(minus, lower.tail=TRUE, log.p=TRUE)
    pminus <- pminus + log(2) + log1p(exp(pminus) / -2)
    maxneg <- qnorm(pminus - log(2), lower.tail=TRUE, log.p=TRUE)
    pes <- pmax(-1, pmin(1, nes / abs(ifelse(nes > 0, maxpos, maxneg))))
    nes <- matrix(nes, nrow=r, ncol=n)
    pes <- matrix(pes, nrow=r, ncol=n)
    dimnames(nes) <- dimnames(pes) <- list(colnames(X), task$sample.names)
    list(nes=nes, pes=pes)
}

matrixNaRnEA.viper <- function(eset, regulon, minsize=25, seed=1, cores=1) {
    if (is.null(ncol(eset))) eset <- matrix(eset, ncol=1L, dimnames=list(names(eset), NULL))
    genes <- rownames(eset)
    if (is.null(genes)) stop("NaRnEA requires row names on the signature matrix.", call.=FALSE)
    good <- vapply(regulon, function(x) !is.null(x$tfmode) && !is.null(x$likelihood), logical(1))
    regulon <- regulon[good]
    if (!length(regulon)) stop("No valid regulons were supplied.", call.=FALSE)
    regulator.names <- names(regulon)
    if (is.null(regulator.names)) regulator.names <- as.character(seq_along(regulon))
    targets <- lapply(regulon, function(x) intersect(names(x$tfmode), genes))
    keep <- lengths(targets) >= minsize
    regulon <- regulon[keep]; targets <- targets[keep]
    if (!length(regulon)) stop("There are no regulons with enough targets for NaRnEA.", call.=FALSE)
    regulator.names <- regulator.names[keep]
    set.seed(seed)
    for (j in seq_len(ncol(eset))) {
        x <- eset[, j]
        if (anyNA(x)) stop("NaRnEA does not accept missing values in the signature.", call.=FALSE)
        iz <- which(x == 0)
        if (length(iz)) {
            nonzero <- x[x != 0]
            if (!length(nonzero)) stop("NaRnEA cannot rank a signature column containing only zeros.", call.=FALSE)
            probs <- c(sum(nonzero < 0), sum(nonzero > 0))
            if (!sum(probs)) probs <- c(0.5, 0.5) else probs <- probs / sum(probs)
            x[iz] <- runif(length(iz), 0, min(abs(nonzero))) * sample(c(-1, 1), length(iz), replace=TRUE, prob=probs)
            eset[, j] <- x
        }
    }
    R <- matrixStats::colRanks(abs(eset), ties.method="random", preserveShape=TRUE)
    S <- sign(eset)
    g <- nrow(eset); n <- ncol(eset); r <- length(regulon)
    reg.data <- vector("list", r)
    max.du <- matrix(0, r, 2L)
    for (k in seq_len(r)) {
        x <- regulon[[k]]
        ix <- match(targets[[k]], names(x$tfmode))
        am <- as.numeric(x$tfmode[ix]); aw <- as.numeric(x$likelihood[ix])
        if (any(!is.finite(aw)) || any(aw <= 0) || any(!is.finite(am)) || any(abs(am) > 1))
            stop("NaRnEA requires positive finite likelihoods and finite tfmode values in [-1, 1].", call.=FALSE)
        am[am == 1] <- 0.999; am[am == -1] <- -0.999
        iz <- which(am == 0)
        if (length(iz)) am[iz] <- sample(c(0.001, -0.001), length(iz), replace=TRUE)
        row <- match(targets[[k]], genes)
        reg.data[[k]] <- list(row=row, am=am, aw=aw)
        ord <- order(aw, decreasing=TRUE)
        mag <- seq.int(g, g + 1L - length(aw))
        max.du[k, ] <- c(sum(aw[ord] * mag * abs(am[ord])), sum(aw[ord] * mag * (1 - abs(am[ord]))))
    }
    lens <- vapply(reg.data, function(x) length(x$row), integer(1))
    ii <- unlist(lapply(reg.data, `[[`, "row"), use.names=FALSE)
    jj <- rep.int(seq_len(r), lens)
    awam <- unlist(lapply(reg.data, function(x) x$aw * x$am), use.names=FALSE)
    awund <- unlist(lapply(reg.data, function(x) x$aw * (1 - abs(x$am))), use.names=FALSE)
    X <- Matrix::sparseMatrix(i=ii, j=jj, x=awam, dims=c(g, r), dimnames=list(genes, regulator.names))
    U <- Matrix::sparseMatrix(i=ii, j=jj, x=awund, dims=c(g, r), dimnames=list(genes, regulator.names))
    cores <- min(as.integer(cores[1L]), n)
    if (is.na(cores) || cores < 1L) cores <- 1L
    if (cores > 1L && n > 1L) {
        groups <- parallel::splitIndices(n, min(n, cores * 2L))
        parts <- .viperParallelApply(groups, function(ix, X, U, R, S, max.du, g, sample.names) {
            .viperNaRnEAChunk(list(X=X, U=U, R=R[, ix, drop=FALSE], S=S[, ix, drop=FALSE],
                                   max.du=max.du, g=g, sample.names=sample.names[ix]))
        }, X=X, U=U, R=R, S=S, max.du=max.du, g=g,
            sample.names=colnames(eset), mc.cores=cores)
        nes <- do.call(cbind, lapply(parts, `[[`, "nes"))
        pes <- do.call(cbind, lapply(parts, `[[`, "pes"))
        list(es=nes, nes=nes, pes=pes)
    } else {
        z <- .viperNaRnEAChunk(list(X=X, U=U, R=R, S=S, max.du=max.du,
                                    g=g, sample.names=colnames(eset)))
        list(es=z$nes, nes=z$nes, pes=z$pes)
    }
}

#' analytic Rank-based Enrichment Analysis
#' 
#' This function performs wREA enrichment analysis on a set of signatues
#' 
#' @param eset Matrix containing a set of signatures, with samples in columns and traits in rows
#' @param regulon Regulon object
#' @param method Character string indicating the implementation, either auto, matrix or loop
#' @param minsize Interger indicating the minimum allowed size for the regulons
#' @param cores Integer number of worker processes. Values above 1 use PSOCK on Windows and fork workers on Unix.
#' @param wm Optional numeric matrix of weights (0; 1) with same dimension as eset
#' @param verbose Logical, whether a progress bar should be shown
#' @return List of two elements, enrichment score and normalized enrichment score
#' @details In the loop implementation, \code{cores > 1} enables PSOCK workers on Windows and fork workers on Unix. Nested calls reuse the current worker layer. The Windows aggregate input-copy budget is controlled by \code{options(viper.max.parallel.memory = ...)} and defaults to 64 GiB.
#' @export

aREA <- function(eset, regulon, method=c("auto", "matrix", "loop"), minsize=20, cores=1, wm=NULL, verbose=FALSE) {
    method <- match.arg(method)
    if (is.null(ncol(eset))) eset <- matrix(eset, length(eset), 1, dimnames=list(names(eset), NULL))
    if (minsize>0) {
        regulon <- lapply(regulon, function(x, genes) {
            pos <- names(x$tfmode) %in% genes
            list(tfmode=x$tfmode[pos], likelihood=x$likelihood[pos])
        }, genes=rownames(eset))
        regulon <- regulon[sapply(regulon, function(x) length(x$tfmode))>=minsize]
        if (length(regulon)==0) stop(paste("There are no regulons with size of at least ", minsize, " targets.", sep=""), call.=FALSE)
        class(regulon) <- "regulon"
    }
    targets <- unique(unlist(lapply(regulon, function(x) names(x$tfmode)), use.names=FALSE))
    if (length(which(is.na(eset)))>0) method <- "loop"
    if (method=="auto") {
        method <- "matrix"
        if (length(targets)>1000) method <- "loop"
    }
    if (length(wm)>0 | length(which(is.na(eset)))>0) method <- "loop"
    switch(method,
    matrix={
        mor <- sapply(regulon, function(x, genes) {
            return(x$tfmode[match(genes, names(x$tfmode))])
        }, genes=targets)
        wts <- sapply(regulon, function(x, genes) {
            tmp <- x$likelihood[match(genes, names(x$tfmode))]
            tmp[is.na(match(genes, names(x$tfmode)))] <- NA
            return(tmp/max(tmp, na.rm=T))
        }, genes=targets)
        mor[is.na(mor)] <- 0
        wts[is.na(wts)] <- 0
        nes <- sqrt(colSums(wts^2))
        wts <- scale(wts, center=FALSE, scale=colSums(wts))
        pos <- match(targets, rownames(eset))
        t2 <- matrixStats::colRanks(eset, ties.method="average", preserveShape=TRUE)/(nrow(eset)+1)
        t1 <- abs(t2-.5)*2
        t1 <- t1+(1-max(t1))/2
        t1 <- qnorm(filterRowMatrix(t1, pos))
        t2 <- qnorm(filterRowMatrix(t2, pos))
        sum1 <- t(mor * wts) %*% t2
        sum2 <- t((1-abs(mor)) * wts) %*% t1
        ss <- sign(sum1)
        ss[ss==0] <- 1
        tmp <- (abs(sum1) + sum2*(sum2>0))*ss
        tmp <- list(es=tmp, nes=tmp*nes)
    },
    loop={
        t2 <- sweep(matrixStats::colRanks(eset, ties.method="average", preserveShape=TRUE, na.last="keep"), 2, colSums(!is.na(eset))+1, "/")
        t1 <- abs(t2-.5)*2
        t1 <- t(t(t1)+(1-apply(t1, 2, max, na.rm=TRUE))/2)
        t1 <- qnorm(t1)
        t2 <- qnorm(t2)
        if (!is.null(wm)) {
            if (is.null(ncol(wm))) wm <- matrix(wm, length(wm), ncol(eset), dimnames=list(names(wm), colnames(eset)))
            wm <- filterRowMatrix(wm, match(rownames(eset), rownames(wm)))
            rownames(wm) <- rownames(eset)
            wm[is.na(wm)] <- 0
        }
        if (!is.null(wm)) wm[is.na(t1)] <- 0
        t1[is.na(t1)] <- 0
        t2[is.na(t2)] <- 0
        pb <- NULL
        if (cores>1) {
            temp <- .viperParallelApply(1:length(regulon), function(i, regulon, t1, t2, ws) {
                x <- regulon[[i]]
                pos <- match(names(x$tfmode), rownames(t1))
                if (is.null(ws)) {
                    sum1 <- crossprod(x$tfmode * x$likelihood, t2[pos, , drop=FALSE])
                    sum2 <- crossprod((1-abs(x$tfmode)) * x$likelihood, t1[pos, , drop=FALSE])
                    ss <- sign(sum1); ss[ss==0] <- 1
                    return(as.vector((abs(sum1) + sum2*(sum2>0)) / sum(x$likelihood) * ss))
                }
                sum1 <- matrix(x$tfmode * x$likelihood, 1, length(x$tfmode)) %*% (filterRowMatrix(t2, pos) * filterRowMatrix(ws, pos))
                ss <- sign(sum1)
                ss[ss==0] <- 1
                sum2 <- matrix((1-abs(x$tfmode)) * x$likelihood, 1, length(x$tfmode)) %*% (filterRowMatrix(t1, pos) * filterRowMatrix(ws, pos))
                return(as.vector(abs(sum1) + sum2*(sum2>0)) / colSums(x$likelihood * filterRowMatrix(ws, pos)) * ss)
            }, regulon=regulon, t1=t1, t2=t2, mc.cores=cores, ws=wm)
            temp <- sapply(temp, function(x) x)    
        }
        else {
            if (verbose) {
                pb <- txtProgressBar(max=length(regulon), style=3)
            }
            temp <- sapply(1:length(regulon), function(i, regulon, t1, t2, pb, ws) {
                x <- regulon[[i]]
                pos <- match(names(x$tfmode), rownames(t1))
                if (is.null(ws)) {
                    sum1 <- crossprod(x$tfmode * x$likelihood, t2[pos, , drop=FALSE])
                    sum2 <- crossprod((1-abs(x$tfmode)) * x$likelihood, t1[pos, , drop=FALSE])
                    ss <- sign(sum1); ss[ss==0] <- 1
                    if (is(pb, "txtProgressBar")) setTxtProgressBar(pb, i)
                    return(as.vector((abs(sum1) + sum2*(sum2>0)) / sum(x$likelihood) * ss))
                }
                sum1 <- matrix(x$tfmode * x$likelihood, 1, length(x$tfmode)) %*% (filterRowMatrix(t2, pos) * filterRowMatrix(ws, pos))
                ss <- sign(sum1)
                ss[ss==0] <- 1
                sum2 <- matrix((1-abs(x$tfmode)) * x$likelihood, 1, length(x$tfmode)) %*% (filterRowMatrix(t1, pos) * filterRowMatrix(ws, pos))
                if (is(pb, "txtProgressBar")) setTxtProgressBar(pb, i)
                return(as.vector(abs(sum1) + sum2*(sum2>0)) / colSums(x$likelihood * filterRowMatrix(ws, pos)) * ss)
            }, regulon=regulon, t1=t1, t2=t2, pb=pb, ws=wm)
        }
        if (is.null(ncol(temp))) temp <- matrix(temp, 1, length(temp))
        colnames(temp) <- names(regulon)
        rownames(temp) <- colnames(eset)
        if (!is.null(wm) && length(which(wm<1))>0) {
            w <- sapply(regulon, function(x, ws) {
                tmp <- x$likelihood*filterRowMatrix(ws, match(names(x$tfmode), rownames(ws)))
              sqrt(colSums(apply(tmp, 2, function(x) x/max(x))^2))
            }, ws=wm)
            if (is.null(ncol(w))) w <- t(w)
            w <- t(w)
        }
        else {
            w <- sapply(regulon, function(x) sqrt(sum((x$likelihood/max(x$likelihood))^2)))
        }
        return(list(es=t(temp), nes=t(temp)*w))
    })
    return(tmp)
}
